### ISSUE TITLE
Support wizard form?

### ISSUE THREAD

**Issue by WangLarry** [yahoo/jafar#46]
**Is your feature request related to a problem? Please describe.**
I have a form with lots of fields, which be filled with some peoples, everyone can only fill limited  fields.

**Describe the solution you'd like**
I wish jafar can support wizard form, can define each step of form, which control validations, required etc.

Thanks for your great library. Clean code and good document.

**Comment by galhavivi** [comment]
We currently dont have a wizard layout yet (which allow "next, next.." for each step), but its on the table :)
for now please look the item layout -> tabs - its pretty close to wizard support

https://yahoo.github.io/jafar/demo-react-layout.html#/item/layouts/html

**Comment by galhavivi** [comment]
pr - https://github.com/yahoo/jafar/pull/61

Added demo for form wizard - https://yahoo.github.io/jafar/react-layout/#/item/wizard/html

I actually didnt create any new component - just organised sections to render according to a specific step.
The good thing about Jafar is that it let you render and field wherever you wish for as long as it lives under a Form component, and you can choose to look on any data of the form - in this case I disabled the "Next" button if some current step section's fields are invalid.
