### ISSUE TITLE
'react editor' link is broken

### ISSUE THREAD

**Issue by WangLarry** [yahoo/jafar#59]
In  "https://yahoo.github.io/jafar/docs/react-demos.html" page in Jafar website, the "react editor" link is not correct.

![Snip20200706_1](https://user-images.githubusercontent.com/5869244/86590345-fea45f80-bfc1-11ea-80bf-59f4ee60ecac.png)

It should be same as url in top menubar: https://yahoo.github.io/jafar/demo-react-editor.html

**Comment by galhavivi** [comment]
@WangLarry Good catch :) 10x!
actually all 4 links in this doc are broken and should be the same as the header..
its a good first issue ;)

**Comment by galhavivi** [comment]
pr - https://github.com/yahoo/jafar/pull/64
