### ISSUE TITLE
The description of 'Path'  in document is wrong. 

### ISSUE THREAD

**Issue by WangLarry** [yahoo/jafar#69]
In https://yahoo.github.io/jafar/docs/path.html, the following description is wrong, which is about 'Dirty' actually.

> Path
Form / Field dirty flags are calculate on each relevant action such as init, change value and change data.
This does not need to be passed by default in the initial form model json. You can pass it in the initial form model json, if you are currently loading a form model from persist model (i.e you saved the form model before user did page reload - and want to reload the form with the exact same model state that it was before the refresh)

**Comment by galhavivi** [comment]
@WangLarry Thank you dear!
