### ISSUE TITLE
rect-editor - support fields library

### ISSUE THREAD

**Issue by WangLarry** [yahoo/jafar#75]
**Is your feature request related to a problem? Please describe.**
Forms often have similar fields, which have some same infos. Currently we need define fields from zero, which is not handy.

**Describe the solution you'd like**
If having a field library, we can import infos of field from it, then generate form quickly.

**Comment by galhavivi** [comment]
@WangLarry What did you have in mind for example?

To me it sounds like it should be implemented in the "app level" or "organization level" - to have a private set of fields packed together in a package of common fields that can be consumed from different places in the organization / app.

(we used similar approach in our apps)

**Comment by WangLarry** [comment]
I mean editor support this feature and interface.

**Comment by galhavivi** [comment]
@WangLarry Cool for editor its a good idea!
for now we have the option of "duplicate" form or duplicate field inside a specific form..
but a shared fields library is interesting. Will think about how to do it :)

**Comment by galhavivi** [comment]
pr - https://github.com/yahoo/jafar/pull/81

deployed - https://yahoo.github.io/jafar/demo-react-editor.html
